version: '3'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9090:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://t75-sonarcloud.ci2n7dw776xd.us-east-1.rds.amazonaws.com/sonarcloud
      - SONAR_JDBC_USERNAME=sonar_usr
      - SONAR_JDBC_PASSWORD=z3XLYoLUbg9IYJ86RN7QjmZQFYCjQYaU

    # depends_on:
    #   - sonar-db
    networks:
      - sq-net

  # sonar-db:
  #   image: postgres:15
  #   container_name: sonar-postgres
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #     - POSTGRES_DB=sonar
  #   volumes:
  #     - ./sonar_data:/var/lib/postgresql/data
  #   networks:
  #     - sq-net

networks:
  sq-net:
    driver: bridge
