# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t75-sa-eks-ec2
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${var.ACCOUNT_ID}:role/t75-eks-cluster-role