name: Teardown

on:
  workflow_dispatch:

jobs:
  terraform-teardown:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout infrastructure
      uses: actions/checkout@v4
      with: 
        ref: tcg-v4 # only to separate tech challenge versions

    - name: Configure AWS user credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy --auto-approve
